### ISSUE TITLE
Orientation issue

### ISSUE THREAD

**Issue by Flashsolutions** [goldhuang/PerfectImageCropper#2]
Photos taken with portrait orientation do not size correctly in the cropped image  
![img_2694](https://cloud.githubusercontent.com/assets/60280/2559593/57cbdb8c-b782-11e3-9033-39db617460ee.PNG)
![img_2695](https://cloud.githubusercontent.com/assets/60280/2559594/5a1d3336-b782-11e3-9bee-7e4ddec797c0.PNG)

**Comment by jbiscarri** [comment]
You have to fix image orientation before assigning image property.
Here you have an example:
```
- (UIImage *)normalizedImage:(UIImage *)image {
    if (image.imageOrientation == UIImageOrientationUp) return image;    
    UIGraphicsBeginImageContextWithOptions(image.size, NO, image.scale);
    [image drawInRect:(CGRect){0, 0, image.size}];
    UIImage *normalizedImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return normalizedImage;
}
```
